### PR TITLE
Complete landing page

### LINKED ISSUE #33: Home page mapping + background
image
Add background image to home page + edit nav bar to make the ISA icon take you back to the home page (dont worry about the upcoming events yet)

### PR DESCRIPTION
**Pull request by MarcusHsieh**
- Created event cards 
  - Created `data/landing/tempData.ts` for temporary display

image

### CODE REVIEW

**Review by kavinphab — COMMENTED** [review]
remove about us, extend page to show entire picture

**Comment by kavinphab** [comment]
image
mission is missing from navbar, remove filler text between Iranian Student Association and the upcoming events, add خوش آمدید (it means welcome in Persian, add it in bigger text, see how it looks otherwise we can just leave it blank)

**Comment by MarcusHsieh** [comment]
image

**Comment by kavinphab** [comment]
image
make responsive, implement sandwich at smaller screen sizes (like other nav bar), shrink icon, title, and upcoming events at smaller screen sizes, set default state of upcoming events cards to say no upcoming events

**Review by kavinphab — APPROVED** [review]

**Pull request merged**
