### PR TITLE
footer .tsx

### LINKED ISSUE #6: Footer Component
image
Will be used on multiple pages
components/footer.tsx

### PR DESCRIPTION
**Pull request by HaokunYang123**
image

### CODE REVIEW

**Comment by HaokunYang123** [comment]
I cant find the background image like the lines of temple thing

**Comment by HaokunYang123** [comment]
image

**Comment by kavinphab** [comment]
Footer is too big, reduce the size of the image text and icons, move footer data to data folder, add footer to layout.tsx so it is displayed on every page (put it under children)

**Comment by HaokunYang123** [comment]
image

**Comment by kavinphab** [comment]
image
Bottom row of footer breaks in places where it is cropped, don't worry about this for now I will see if I can get an extended version of this asset

**Review by kavinphab — APPROVED** [review]
Looks good

**Pull request merged**
