### PR TITLE
button component

### LINKED ISSUE #13: Button component
image
We will reuse this in multiple places throughout the website
create in components/button.tsx

### PR DESCRIPTION
**Pull request by apaya22**
Screenshot 2024-10-15 at 10 05 05 PM
 
Finished the basic of the button component, need to ensure I do not have to add anything else to the functionality of the component.

### CODE REVIEW

**Review by kavinphab — COMMENTED** [review]
Use next/link, not button tag, make text bigger, rounder button

**Comment by apaya22** [comment]
Made image rounder, implemented the next/link as well

Screenshot 2024-10-19 at 12 38 55 PM

**Comment by kavinphab** [comment]
refer to the image I posted in your issue for the roundness of the button, make sure you resolve merge conflicts in your branch

**Comment by apaya22** [comment]
made button less round
Screenshot 2024-10-21 at 11 07 48 AM

**Comment by apaya22** [comment]
Also fixed merge conflict

**Comment by kavinphab** [comment]
Make sure you run npm run format, make sure page is rendering and you can check build with npm run build

**Review by kavinphab — CHANGES_REQUESTED** [review]
Looks good but you can implement button like this < Button link="test" txt="Link" / > no need for that closing tag

**Review by kavinphab — APPROVED** [review]

**Pull request merged**
