### PR TITLE
Update Titles

### LINKED ISSUE #48: Update Titles
Figma now has titles for all pages, update titles, add them as images

### PR DESCRIPTION
**Pull request by VindenD**
Updated title for Join Us page
Screenshot 2024-11-07 001231

### CODE REVIEW

**Comment by VindenD** [comment]
Screenshot 2024-11-07 143134
Screenshot 2024-11-07 143119

**Comment by kavinphab** [comment]
Its too big reduce the size to match the titles on the other pages

**Comment by VindenD** [comment]
Screenshot 2024-11-07 152757

**Comment by kavinphab** [comment]
merge conflicts

**Comment by kavinphab** [comment]
image
this is how the join us page looks on my end, pull and run npm run eslint

**Comment by VindenD** [comment]
image

**Review by kavinphab — APPROVED** [review]

**Pull request merged**
